#!/usr/bin/env python3

"""
Main application module

.. todo:: All the "print" should be moved to some logging process...
We need doc
"""

import os
import json
import time

import tkinter
import tkinter.filedialog
import tkinter.messagebox
import tkinter.simpledialog

# tk colors : https://www.tcl.tk/man/tcl/TkCmd/colors.html

from pathlib import Path
from datetime import datetime # datetime.now().strftime('%c')
from pymediainfo import MediaInfo


import utils as U

from infoframe import InfoFrame
from playercontrol import PlayerControl
from applicationmenu import ApplicationMenu
from codingframe import FrameworkFrame
from newcode import NewCode

__version__ = '0.3.0'
__author__ = 'L. Pezard'
__licence__ = 'GPL'

class Application(tkinter.Tk):
    """
    Main codix application class
    """
    def __init__(self):
        tkinter.Tk.__init__(self)
        self.resizable(tkinter.TRUE, tkinter.TRUE)
        # Menu
        self.menu = ApplicationMenu(master=self)
        self['menu'] = self.menu

        # Variables
        self.state = {'media_loaded': False,
                       'code_loaded': False,
                       'data_loaded': False}

# lpcomment: variables attribuées a InfoFrame
#        self.code_file = tkinter.StringVar()
#        self.media_file = tkinter.StringVar()
#        self.data_file = tkinter.StringVar()
        # variables related to player
#FIXME: keep player_mode and period_display temporarily for encodingframe
# They are not needed for player_control which have its own properties
#        self.player_mode = tkinter.StringVar(value='')
#        self.period_display = tkinter.StringVar(value='')
#        self.time_display = tkinter.StringVar(value='')

        self.current_time = None # in ms
        self.current_step = None
        self.max_step = None
        self.max_time = None # in ms. will be overwritten when media is read

# FIXME: what is the difference between: is_recording and is_set_start_time?
#        self.is_recording = False
#        self.is_set_start_time = False

        self.container = {'history': [], # [(date, observer, comment), ...]
                          'media': '', # path for the media file
                          'code': {}, # dictionary from the code file
                          'times': [], # sample times (in ms) vlc works with milliseconds
                          'comments': [], # sample comments
                          'data': {}} # data
        
        self._context = "standard" # lpcomment: intialize to None?

# Menu related functions
#-----------------------

    def new_code(self):
        """Application for defining a new coding framework.
        """
        self.newcode = NewCode(parent=self)
        self.newcode.grid(row=1, column=1, sticky=U.sticky_all)
        self.menu.disable_actions()

    def start_session(self):
        self.info = InfoFrame(parent=self, 
                              states=(tkinter.NORMAL,    # load media
                                      tkinter.DISABLED,  # load code
                                      tkinter.DISABLED)) # load data
        self.info.grid(row=1, column=1, sticky=U.sticky_all)
        self.menu.disable_actions()

    def retrieve_session(self):
        self.info = InfoFrame(parent=self, 
                              states=(tkinter.DISABLED, # load code
                                      tkinter.DISABLED, # load media
                                      tkinter.NORMAL))  # load data
        self.info.grid(row=1, column=1, sticky=U.sticky_all)
        self.menu.disable_actions()

    def reset(self):
        """Reset the file menu and all the current variables.
        """
        raise NotImplementedError
#        self.info.destroy()
#        self.framework.destroy()
#        self.control.destroy()
#        self.init_variables()

    def help_browser(self):
        self.notimplemented()

    def aboutHandler(self):
        self.notimplemented()

    def make_media_player(self, fname):
        """
        create a player control frame
        """
        self.control = PlayerControl(parent=self, file_name = fname)
        self.control.grid(row=1, column=0, sticky=U.sticky_all)

    def make_coding_frame(self, fname):
        """
        creates the coding frame
        """
        self.framework = FrameworkFrame(parent=self, filename=fname)
        self.framework.grid(row=2, column=0, sticky=U.sticky_all)

    def save(self):
        filename = self.data_file.get()
        datafile = open(filename, 'w')
        json.dump(self.container, datafile)
        datafile.close()
        print('Data saved in %s' % filename)
    
    def save_as(self):
        filename = tkinter.filedialog.asksaveasfilename()
        # FIXME: does not work if file already exists
        if U.is_valid_filename(filename):
            datafile = open(filename, 'w')
            json.dump(self.container, datafile)
            datafile.close()
            print('Data saved in %s' % filename)
            self.data_file.set(filename)
            self.menu.fileMenu.entryconfig(8, state=tkinter.NORMAL) # Save
            self.menu.fileMenu.entryconfig(9, state=tkinter.DISABLED) # Save as
        else:
            tkinter.messagebox.showinfo('File not saved', 'File has not been saved')

    def save_data(self):
        if self.data_file.get() == '':
            self.save_as()
        else:
            self.save()
    
    def get_state(self):
        # return self.control._state
        return self.control.state
    def get_mode(self):
        # return self.control._mode
        return self.control.mode


    @property
    def context(self):
         return self._context

    @context.setter
    def context(self, value):
        if value == "processing":
            self._context = "processing"
            self.control.config_buttons({self.control.play_but : 'normal', 
                                    self.control.back_but : 'disabled',
                                    self.control.forward_but : 'disabled', 
                                    self.control.mode_check : 'disabled',
                                    self.control.period_ent : 'disabled',
                                    self.control.time_ent: 'disabled'})


# Coding framework related functions
#-----------------------------------
#    def start_processing(self):
#        """
#        Start processing and fill the container with:
#        - observer, date, comments
#        - start time
#        - code and media file names
#        - encoding specifications 
#        """
#        self.control.config_buttons({self.control.play_but : 'disabled', 
#                                    self.control.back_but : 'disabled',
#                                    self.control.forward_but : 'disabled', 
#                                    self.control.mode_check : 'disabled',
#                                    self.control.period_ent : 'disabled'})
#        
#
#        observer = self.framework.spec_frame.person.get()
#        while observer == '' or observer is None :
#            name = tkinter.simpledialog.askstring('Please identify', 'Please identify yourself')
#            observer = name
#            self.framework.spec_frame.person.set(name)
#        
#        date = datetime.now().strftime('%c')
#        self.framework.spec_frame.timestamp.set(date)
#        comment = self.framework.spec_frame.comment.get()
#        self.container['history'].append((date, observer, comment))
#
#        if self.data_loaded: # resume session
#            self.control.set_time(self.container['times'][0], msg='Start processing')
#            self.current_step = 0
#            self.max_step = len(self.container['times'])
#            
#        else: # starts a new session
## lpcomment: les boutons doivent être désactivés au début. Ils ne sont activés
## qu'à la pause après la première période de "play".
## Le coding frame doit imposer ses valeurs au player au moment du "start
## processing"
#            self.container['media'] = self.media_file.get()
#
#            #self.get_mode_and_period(self.container['code'])
#            self.control.mode = self.framework.player_mode.get()
#            self.control.period = self.framework.period_display.get()
#            self.framework.config_specifications('disabled')
#
## FIXME: mode appartient au player mais pas à l'application
##            mode = self.player_mode.get()
## FIXME: change control for player?
#            mode = self.control.mode
#            if mode == 'regular': # regular sampling
#                #period = self.control.get_period()
#                period = self.control.period
#                if period is not None:
#                    self.freeze()
#                print('period: ', period)
#                assert(len(self.container['times']) == 0)
#                self.container['times'].append(self.current_time)
#                self.max_step = len(self.container['times']) - 1
#                self.current_step = 0
#                self.data_loaded = True
#                print(self.container)
#                self.info.data_save.configure(state=tkinter.NORMAL)
#    #                    if self.current_step == 0 or \
#    #                       self.control.player.get_state() == 3: # playing
#    #                    while self.control.player.get_state() != 5: # 5: Stopped
#    #                        print(self.control.player.get_state())
#    #                        # time.sleep(5)
#                if self.control._state == 'paused': 
#                    self.current_step += 1
#                    print("current step: ", self.current_step)
#    #                        self.config_processing_buttons('normal')
#            else:
#                raise NotImplementedError('Continuous coding is not implemented')
#            
#            self.framework.config_processing_buttons('normal')
#
##
##                # self.current_step = 0
##
###            if not self.data_loaded:
###                self.container['times'][0] = self.current_time
###                self.is_set_start_time = True
###                self.control.set_time(self.current_time, msg='Start processing')
###            else:
###                self.control.set_time(self.container['times'][0], msg='Start processing')
###            self.set_step(0)
###            self.is_recording = True
###
###            self.control.forward_but.configure(state=tkinter.NORMAL)
###            self.control.back_but.configure(state=tkinter.NORMAL)
###
###            FrameworkFrame.config_specifications('disabled')
###            self.info.code_load.configure(state=tkinter.DISABLED)
###            self.info.media_load.configure(state=tkinter.DISABLED)
###   #         self.menu.fileMenu.entryconfig(8, state=Tkinter.NORMAL) # Save
###            self.menu.fileMenu.entryconfig(9, state=tkinter.NORMAL) # Save as
###            self.info.data_save.configure(state=tkinter.NORMAL)
###                self.period_display.set(str(period))
###                self.dt = int(float(period) * 1000)
###                print('dt: ', self.dt)
###                self.control.step_check.select()
###                self.control.pause_but.configure(state=tkinter.DISABLED)
###                # can't go back 
###                self.control.back_but.configure(state=tkinter.DISABLED)
##                else:
##                    raise NotImplementedError('Continuous coding is not implemented')
###                self.player_mode.set('continuous')
###                self.control.step_check.deselect()
###                self.control.back_but.configure(state=Tkinter.DISABLED)
###            step = self.framework.spec_frame.step.get()
###            self.period_display.set(step)
###           #  self.freeze_step()
##
##                print('period: ', period)
##                self.data_loaded = True
##                assert(len(self.container['times']) == 0)
##                self.container['times'].append(self.current_time)
##                # self.current_step = 0
##
###            if not self.data_loaded:
###                self.container['times'][0] = self.current_time
###                self.is_set_start_time = True
###                self.control.set_time(self.current_time, msg='Start processing')
###            else:
###                self.control.set_time(self.container['times'][0], msg='Start processing')
###            self.set_step(0)
###            self.is_recording = True
###
###            self.control.forward_but.configure(state=tkinter.NORMAL)
###            self.control.back_but.configure(state=tkinter.NORMAL)
###
###            FrameworkFrame.config_specifications('disabled')
###            self.info.code_load.configure(state=tkinter.DISABLED)
###            self.info.media_load.configure(state=tkinter.DISABLED)
###   #         self.menu.fileMenu.entryconfig(8, state=Tkinter.NORMAL) # Save
###            self.menu.fileMenu.entryconfig(9, state=tkinter.NORMAL) # Save as
###            self.info.data_save.configure(state=tkinter.NORMAL)
##            while self.control.player.get_state() != 5: # 5: Stopped
##               if self.control.player.get_state() == 4: # 4: Paused
##                   self.framework.config_processing_buttons('normal')
##                   print(self.container)
#
#    def display_codes(self, step):
#        # self.framework.config_processing_buttons('normal')
#        panellist = self.framework.coding_frame.panels
#        for pan in panellist:
#            # pan.name = recording site
#            for cname, v in pan.coding.items():
#            # cname = code_name
#                sequence = self.container['data'][pan.name][cname]['seq']
#                local_int = sequence[step]
#                local_str = self.int2str[pan.name][cname][local_int]
#                v['var'].set(local_str)
#        comment = self.container['comments'][step]
#        self.framework.coding_frame.comment.set(comment)
#    
#    def erase_codes(self):
#        panellist = self.framework.coding_frame.panels
#        for pan in panellist:
#            # pan.name = recording site
#            for cname, v in pan.coding.items():
#            # cname = code_name
#                v['var'].set('')
#        self.framework.coding_frame.comment.set('')
#
#    def record_state(self):
#        """
#        Record a step
#        """
#        # local "pointers"
#
#        ##  leocomment a mettre a la fin 
#        """ self.control.config_buttons({self.control.play_but : 'normal', 
#                                        self.control.back_but : 'normal',
#                                        self.control.forward_but : 'normal', 
#                                        self.control.mode_check : 'normal',
#                                        self.control.period_ent : 'normal'})
#        self.framework.config_processing_buttons('disabled') """
#        
#        
#        panellist = self.framework.coding_frame.panels
#        times = self.container['times']
#        comments = self.container['comments']
#
#        #mode = self.player_mode.get()
#        print(" Current step " , self.current_step)
#        mode = self.control.mode
#        if mode == 'regular': # regular sampling
#            if self.current_step < 0: # Should not happen...
#                tkinter.messagebox.showinfo('Before beginning', 'Before beginning')
#                return
#            elif self.current_step > len(times):
#                tkinter.messagebox.showinfo('Discontinuous coding', 
#                                      'Discontinuous coding')
#                return
#            else:
#                # First passage for checking presence of all symbols
#                tmp_symbol = {}
#                for pan in panellist:
#                    tmp_symbol[pan.name] = {}
#                    # print pan.name # rec_site
#                    for cname,v in pan.coding.items():
#                    # k: code_name
#                        symbol = v['var'].get()
#                        # sequence = self.container['data'][pan.name][cname]['seq']
#                        if symbol == '':
#                            tkinter.messagebox.showinfo('Code missing', 'A code is missing')
#                            return
#                        else:
#                            # sequence.append(self.str2int[pan.name][cname][symbol])
#                            tmp_symbol[pan.name][cname] = symbol
#                
#                local_comment = self.framework.coding_frame.comment.get()
#
#                # Seconde passage to record the symbol
#                print('ct_step', self.current_step, 'ct_time', self.current_time, 'time', times)
#
#                if self.current_step == len(times):
#                    print('==')
#                    times.append(self.current_time)
#                    comments.append(local_comment)
#                    
#                    for pan in panellist:
#                        # print pan.name # rec_site
#                        for cname,v in pan.coding.items():
#                            sequence = self.container['data'][pan.name][cname]['seq']
#                            tsymbol = tmp_symbol[pan.name][cname]
#                            print(sequence, tsymbol)
#                            sequence.append(self.str2int[pan.name][cname][tsymbol])
#                        print(str(sequence))
#                else:
#                    print('else')
#                    times[self.current_step] = self.current_time
#                    comments[self.current_step ] = local_comment
#                    for pan in panellist:
#                        # print pan.name # rec_site
#                        for cname,v in pan.coding.items():
#                            sequence = self.container['data'][pan.name][cname]['seq']
#                            tsymbol = tmp_symbol[pan.name][cname]
#                            print(sequence, tsymbol)
#                            sequence[self.current_step ] = self.str2int[pan.name][cname][tsymbol]
#                      
#            try:
#                self.display_codes(self.current_step)
#            except IndexError:
#                self.erase_codes()
#            self.framework.disable_codes()
#            print(self.container)
#            self.save_data()
#
#        else: # continuous coding
#            raise NotImplementedError

    def disable_load_data(self):
        self.menu.fileMenu.entryconfig(4, state=tkinter.DISABLED)
        self.info.data_load.config(state=tkinter.DISABLED)

    def disable_load_media(self):
        self.menu.fileMenu.entryconfig(3, state=tkinter.DISABLED)
        self.info.media_load.config(state=tkinter.DISABLED)
    
    def disable_load_code(self):
        self.menu.fileMenu.entryconfig(2, state=tkinter.DISABLED)
        self.info.code_load.config(state=tkinter.DISABLED)
    
    def enable_load_data(self):
        self.menu.fileMenu.entryconfig(4, state=tkinter.NORMAL)
        self.info.data_load.config(state=tkinter.NORMAL)

    def freeze(self):
        """ cannot change step
        """
        self.control.mode_check.configure(state=tkinter.DISABLED)
        self.control.period_ent.configure(state=tkinter.DISABLED)
        self.control.time_ent.configure(state=tkinter.DISABLED)

#    def get_mode_and_period(self, encoding):
#        period = encoding['period']
#
#        if period is None:
#            # self.player_mode.set("continuous")
## FIXME: est que player ne serait pa mieux que control?
#            self.control.mode = "continuous"
#            tkinter.messagebox.showinfo('Continuous not implemented', 
#                                   'Irregular sampling not implemented')
#            raise NotImplementedError()
#        else:
#            #self.player_mode.set("regular")
#            self.control.mode = "regular"
#            # self.period_display.set(str(period))

    def notimplemented(self):
        tkinter.messagebox.showinfo('Not implemented', 'Not implemented')

    

if __name__ == "__main__":
    app = Application()
    app.title('Codix - The Swiss knife for coding behaviors - version: %s'\
              % __version__)
    app.mainloop()
