[application]

cwd_file = cwdfile.ini
default_cwd = ~
required_subfolders = media,data

# The layout to use for the encoder interface. Options include 'embedded' or 'detached'. Default is 'embedded'.
encoder_layout = detached

# relief in ['flat', 'raised', 'sunken', 'solid', 'ridge', 'groove']
; Attention ne pas mettre de commentaire en fin de ligne car ils sont récupérés
; avec la valeur qui suit le signe '='

[infoframe]

borderwidth = 2
background = lightsteelblue
disabled_bg = light grey
relief = groove
filename_width = 30
 

[playercontrol]

# The backend to use for the player control. Options include 'vlc' or 'mpv'. Default is 'vlc'.
backend = vlc
borderwidth = 2
background = lightsteelblue
relief = groove

[codingframework]

borderwidth = 2
background = palegoldenrod 
disabled_bg = light gray 
relief = groove 

panel_max = 5

;[newcode]
