;[application]
# relief in ['flat', 'raised', 'sunken', 'solid', 'ridge', 'groove']
; Attention ne pas mettre de commentaire en fin de ligne car ils sont récupérés
; avec la valeur qui suit le signe '='

[infoframe]

borderwidth = 2
background = lightsteelblue
dark_bg = brown
light_bg = coral
disabled_bg = light grey
relief = groove
filename_width = 30
 

[playercontrol]

borderwidth = 2
background = lightsteelblue
dark_bg = black
light_bg = white
relief = groove

[codingframework]

borderwidth = 2
background = palegoldenrod 
disabled_bg = light gray 
relief = groove 

panel_max = 5

;[newcode]
